"""
`tradelab init-strategy NAME` — scaffold a new strategy file from a template.

Generates src/tradelab/strategies/<snake_name>.py and (optionally) appends an
entry to tradelab.yaml so the strategy is immediately runnable via
`tradelab run <name>`.

Two templates:
  --type=simple   (default) SimpleStrategy with entry_signal/entry_score
  --type=advanced full Strategy with generate_signals (column-level control)
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Optional

import typer
from rich.console import Console


console = Console()


_SIMPLE_TEMPLATE = '''"""
{class_name} — {description}

Generated by `tradelab init-strategy {name} --type=simple`.
Override entry_signal() (and optionally entry_score) below.

Indicators available on `row` (already enriched by tradelab.marketdata.enrich):
  Open, High, Low, Close, Volume,
  ATR, ATR_pct, RSI,
  EMA10, EMA21,
  SMA10, SMA21, SMA50, SMA200,
  Vol_MA20, Vol_Ratio, Vol_OK,
  Trend_OK, Above50, Above200, Pocket_Pivot,
  RS_21d  (relative strength vs SPY over 21 bars)
"""
from __future__ import annotations

from typing import Optional

import pandas as pd

from .simple import SimpleStrategy


class {class_name}(SimpleStrategy):
    name = "{name}"
    timeframe = "1D"
    requires_benchmark = True   # set False if you don't use RS_21d

    default_params = {{
        # Strategy-specific params here:
        # "rsi_threshold": 30.0,

        # Engine-required exit params (the trailing-stop logic uses these):
        "stop_atr_mult": 1.5,
        "trail_tight_mult": 1.0,
        "trail_wide_mult": 2.0,
        "trail_tighten_atr": 1.5,
    }}

    # Optuna search ranges (only for params you want optimized):
    tunable_params = {{
        # "rsi_threshold": (20.0, 50.0),
    }}

    def entry_signal(self, row: pd.Series, prev: Optional[pd.Series], params: dict) -> bool:
        """Return True iff this bar is an entry."""
        if prev is None:
            return False
        # YOUR ENTRY LOGIC HERE. Example:
        # return row["RSI"] < params["rsi_threshold"] and row["Close"] > prev["High"]
        return False

    def entry_score(self, row: pd.Series, prev: Optional[pd.Series], params: dict) -> float:
        """Optional: ranking score when more signals fire than open slots. Higher = better."""
        return 1.0
'''


_ADVANCED_TEMPLATE = '''"""
{class_name} — {description}

Generated by `tradelab init-strategy {name} --type=advanced`.
Use this template when you need full control over the buy_signal /
entry_stop / entry_score columns at vectorised speeds.
"""
from __future__ import annotations

from typing import Optional

import numpy as np
import pandas as pd

from .base import Strategy


class {class_name}(Strategy):
    name = "{name}"
    timeframe = "1D"
    requires_benchmark = True

    default_params = {{
        # Strategy-specific params:

        # Engine-required exit params:
        "stop_atr_mult": 1.5,
        "trail_tight_mult": 1.0,
        "trail_wide_mult": 2.0,
        "trail_tighten_atr": 1.5,
    }}

    tunable_params = {{
        # "param_name": (low, high),
    }}

    def generate_signals(
        self,
        data: dict[str, pd.DataFrame],
        spy_close: Optional[pd.Series] = None,
    ) -> dict[str, pd.DataFrame]:
        p = self.params
        out: dict[str, pd.DataFrame] = {{}}
        for sym, df in data.items():
            df = df.copy()

            # YOUR LOGIC: build a boolean buy_signal column from indicator columns.
            # Example:
            # df["buy_signal"] = (
            #     (df["RSI"] < p["rsi_threshold"])
            #     & df["Trend_OK"]
            #     & (df["Vol_Ratio"] > 1.5)
            # )
            df["buy_signal"] = False

            # Required columns:
            atr_valid = df["ATR"].notna() & (df["ATR"] > 0)
            df["entry_stop"] = df["Close"] - p["stop_atr_mult"] * df["ATR"]
            df["entry_score"] = df.get("RS_21d", 0.0)
            # Mask out warmup bars
            df.loc[~atr_valid, "buy_signal"] = False

            out[sym] = df
        return out
'''


def _to_class_name(snake: str) -> str:
    """foo_bar_baz → FooBarBaz"""
    parts = re.split(r"[_\-\s]+", snake.strip())
    return "".join(part.capitalize() for part in parts if part)


def init_strategy(
    name: str = typer.Argument(..., help="Strategy name (snake_case)"),
    type: str = typer.Option("simple", "--type",
                              help="Template type: 'simple' or 'advanced'"),
    description: str = typer.Option("", help="One-line description for docstring"),
    register: bool = typer.Option(True, "--register/--no-register",
                                    help="Append entry to tradelab.yaml"),
    force: bool = typer.Option(False, "--force",
                                 help="Overwrite if file exists"),
) -> None:
    """Scaffold a new strategy from a template."""
    snake = re.sub(r"[^a-z0-9_]", "", name.lower().replace("-", "_"))
    if not snake or not snake[0].isalpha():
        console.print(f"[red]Invalid name {name!r}; must be snake_case starting with a letter.[/red]")
        raise typer.Exit(2)

    if type not in ("simple", "advanced"):
        console.print(f"[red]Unknown --type {type!r}; expected 'simple' or 'advanced'.[/red]")
        raise typer.Exit(2)

    class_name = _to_class_name(snake)
    desc = description or f"Strategy generated by `tradelab init-strategy {snake}`"

    # Resolve src dir from cwd (assume run from repo root)
    repo_root = Path.cwd()
    strategies_dir = repo_root / "src" / "tradelab" / "strategies"
    if not strategies_dir.exists():
        console.print(f"[red]Cannot find {strategies_dir}. Run from the tradelab repo root.[/red]")
        raise typer.Exit(2)

    out_path = strategies_dir / f"{snake}.py"
    if out_path.exists() and not force:
        console.print(f"[yellow]{out_path} already exists. Pass --force to overwrite.[/yellow]")
        raise typer.Exit(1)

    template = _SIMPLE_TEMPLATE if type == "simple" else _ADVANCED_TEMPLATE
    out_path.write_text(
        template.format(class_name=class_name, name=snake, description=desc),
        encoding="utf-8",
    )
    console.print(f"[green]Created[/green] {out_path}")

    # Append to tradelab.yaml if requested
    yaml_path = repo_root / "tradelab.yaml"
    if register and yaml_path.exists():
        text = yaml_path.read_text(encoding="utf-8")
        if f"  {snake}:\n" in text:
            console.print(f"[dim](already registered in tradelab.yaml; not duplicating)[/dim]")
        else:
            entry = (
                f"\n  {snake}:\n"
                f'    module: "tradelab.strategies.{snake}"\n'
                f'    class_name: "{class_name}"\n'
                f'    description: "{desc}"\n'
                f'    status: "registered"\n'
                f"    params: {{}}\n"
            )
            # Find the strategies: block; append entry there. Heuristic: insert
            # after the s2_pocket_pivot block if present, else at end of strategies:
            # block. Simplest robust thing: find last strategy entry that isn't
            # under a `params:` continuation, then append. But since yaml is
            # whitespace-sensitive, we do it the safe way: find "strategies:"
            # line, find the next top-level key (or EOF), insert before it.
            lines = text.splitlines()
            insert_idx = None
            in_strategies = False
            for i, line in enumerate(lines):
                if line.startswith("strategies:"):
                    in_strategies = True
                    continue
                if in_strategies and line and not line.startswith(" ") and not line.startswith("#"):
                    insert_idx = i
                    break
            if insert_idx is None and in_strategies:
                insert_idx = len(lines)
            if insert_idx is not None:
                new_lines = lines[:insert_idx] + entry.splitlines() + lines[insert_idx:]
                yaml_path.write_text("\n".join(new_lines) + "\n", encoding="utf-8")
                console.print(f"[green]Registered[/green] {snake} in tradelab.yaml")
            else:
                console.print(f"[yellow]Could not find strategies: block in yaml; "
                              f"add manually.[/yellow]")

    console.print()
    console.print(f"Next: edit [cyan]{out_path}[/cyan] and fill in entry_signal()")
    console.print(f"Then: [cyan]tradelab run {snake} --universe smoke_5 --start 2022-01-01[/cyan]")
